# spring配置
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: 118.190.172.85:9200
      connection-timeout: 5s
      readTimeout: 5s
      username: apm_system
      password: F67VtKLgEfGAAu5Lo6gw
