/*
 * This file is generated by jOOQ.
 */
package zcx.jooqdemo.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import zcx.jooqdemo.model.tables.Book;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooqdb extends SchemaImpl {

    private static final long serialVersionUID = 97622766;

    /**
     * The reference instance of <code>jooqdb</code>
     */
    public static final Jooqdb JOOQDB = new Jooqdb();

    /**
     * The table <code>jooqdb.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * No further instances allowed
     */
    private Jooqdb() {
        super("jooqdb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Book.BOOK);
    }
}
