/*
 * This file is generated by jOOQ.
 */
package zcx.jooqdemo.model;


import zcx.jooqdemo.model.tables.Book;


/**
 * Convenience access to all tables in jooqdb
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqdb.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
